# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-xml
      - id: check-json
      - id: check-yaml
        args: [ --allow-multiple-documents ]
      - id: check-toml
      - id: check-merge-conflict
      - id: detect-private-key
      - id: detect-aws-credentials
        args: [ --allow-missing-credentials ]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [ "--profile", "black", "--filter-files", "--line-length", "120" ]

  - repo: https://github.com/psf/black
    rev: 23.1a1
    hooks:
      - id: black
        language_version: python3

  - repo: local
    hooks:
      - id: nb-clear
        name: nb-clear
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert --clear-output --ClearMetadataPreprocessor.enabled=True --inplace

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.1
    hooks:
      - id: nbqa-black
        additional_dependencies: [ black==23.1a1 ]
      - id: nbqa-isort
        additional_dependencies: [ isort==5.12.0 ]
      - id: nbqa-flake8
        additional_dependencies: [ flake8==6.0.0 ]
      - id: nbqa-check-ast
